<?php 
?>

  
  	<aeris-theme id="theme2" active="true" primary="#006699" emphasis="#39B062"> </aeris-theme>
 
 <div style="margin:20px;">
	<formater-catalogue lang="fr" url="https://api.poleterresolide.fr/api"></formater-catalogue>
	</div>
    <!-- The file is generated when we laucnch in console: npm run pre
         then push on github branch master
     Modify the url according to your own configuration -->
	 <script src="https://cdn.rawgit.com/terresolide/formater-catalogue-components-vjs/1.0.0/dist/formater-catalogue-components-vjs.js"></script> 