<?php 
?>

  
  	<aeris-theme id="theme2" active="true" primary="#006699" emphasis="#006699"> </aeris-theme>
 
 <div style="margin:20px;">
	<formater-catalogue lang="fr" url="https://api.poleterresolide.fr/api"></formater-catalogue>
	</div>
    <!-- The file is generated when we laucnch in console: npm run pre
         then push on github branch master
     Modify the url according to your own configuration -->
<script src="https://api.poleterresolide.fr/webcomponents/formater-catalogue-components-vjs_2.3.2.js"></script> 
<!--<script src="http://localhost:8081/dist/build.js"></script>-->
