<?php
?>
<h3>Mise à jour des zones ISGI</h3>
Le résultat n'est pas enregistré mais seulement affiché.<br />
Il s'agit du script <a href="<?=APP_URL?>/draft/zone_isgi/create_isgi_json.php/">/draft/zone_isgi/create_isgi_json.php</a>

<h3>Création des zones</h3>
Comme au dessus, le résultat est seulement affiché pas sauvegardé, le précédent fichier n'est pas écrasé.
<ul>
<li><a href="<?=APP_URL?>/draft/zone_isgi/zone_equatorial.php/">/draft/zone_isgi/zone_equatorial.php</a></li>
<li><a href="<?=APP_URL?>/draft/zone_isgi/zone_auroral_nord.php/">/draft/zone_isgi/zone_auroral_nord.php</a></li>
<li><a href="<?=APP_URL?>/draft/zone_isgi/zone_subauroral.php/">/draft/zone_isgi/zone_subauroral.php</a></li>
<li><a href="<?=APP_URL?>/draft/zone_isgi/zone_polaire.php/">/draft/zone_isgi/zone_polaire.php</a></li>
<li><a href="<?=APP_URL?>/draft/zone_isgi/zone_global.php/">/draft/zone_isgi/zone_global.php</a></li>

</ul>

