<?php 
?>
<div>Il est préférable d'utiliser des fichiers pas trop gros et proches les uns des autres comme </div>
<ul style="float:left; margin:10px 20px;">
<li><a href="https://api.poleterresolide.fr/geotiff/vatican/iw1/geo_filt_20180530-20180623_sd_4rlks_small.tif" download="rome1.tif">rome1</a></li>
<li><a href="https://api.poleterresolide.fr/geotiff/vatican/iw2/geo_filtSW_20180530-20180623_sd_4rlks_small.tif" download="rome2.tif">rome2</a></li>
<li><a href="https://api.poleterresolide.fr/geotiff/vatican/iw3/geo_filt_20180530-20180623_sd_4rlks_small.tif" download="rome3.tif">rome3</a></li>
</ul>
<ul style="float:left;margin: 10px 20px;">
<li><a href="https://api.poleterresolide.fr/geotiff/abana/iw1/geo_filtSW_20180518-20180623_sd_4rlks_small.tif" download="abana1.tif" name="abana1.tif">abana1</a></li>
<li><a href="https://api.poleterresolide.fr/geotiff/abana/iw2/geo_filt_20180518-20180623_sd_4rlks_small.tif" download="abana2.tif">abana2</a></li>
</ul>
<div style="clear:left;"></div>
<geotiff-visualizer  band="2" lang="fr" max-files="3"></geotiff-visualizer>
 <!--  -<formater-map id="test" metadataurl="http://api.formater/geotiff/mexico/info_ft2.json"></formater-map> -->
	 

  <script src="https://api.poleterresolide.fr/webcomponents/formater-geotiff-visualizer-vjs_1.1.0.js"></script> 


