<?php 
?>

  
  	<aeris-theme id="theme2" active="true" primary="#006699" emphasis="#006699"> </aeris-theme>
 
 <div style="margin:20px;">
	<formater-catalogue lang="fr" url="https://api.poleterresolide.fr/api"></formater-catalogue>
	</div>
	<script src="https://api.poleterresolide.fr/webcomponents/formater-catalogue-components-vjs_2.20.3.js"></script>
    <!-- The file is generated when we laucnch in console: npm run pre
         then push on github branch master
     Modify the url according to your own configuration -->
<!--  <script src="https://cdn.rawgit.com/terresolide/formater-catalogue-components-vjs/2.19.0/dist/formater-catalogue-components-vjs.js"></script>--> 

<!--<script src="http://localhost:8081/dist/build.js"></script>-->
