<?php 
?>

  
  	<aeris-theme id="theme2" active="true" primary="#006699" emphasis="#39B062"> </aeris-theme>
  	<div class="formater-default">
  	<header><div><a href="http://isgi.unistra.fr" title="International Service of Geomagnetic Indices"  target="_blank">
  	<img src="https://api.poleterresolide.fr/webcomponents/images/logo_ISGI.png" alt="ISGI" style="max-height:180px;float:left;" class="isgi-logo"></a>
  	</div> <div class="isgi-description"><b>ISGI</b> is the Reference service of the International Association of Geomagnetism and Aeronomy (IAGA) for validation, dissemination and stewardship of geomagnetic indices (with the help of 6 ISGI-Collaborating-Institutes internationally spread) through its official Web portal. <br><br><b>ISGI</b> is an official French National Service of <b>CNRS-INSU</b> which is getting a double label, both in «Solid Earth» <b>TS‑ANO4</b> (National Observation in Magnetism) and in «Astronomy-Astrophysics» <b>AA‑ANO6</b> (Surveillance of the Sun and the Earth's Space Environment).</div></header>
  	<div style="border:1px solid darkred;border-radius:3px; margin:20px 0;padding:10px;font-size:1.5em;color:darkred;">If this message persists, your browser do not support webcomponents. Please use edge, chrome or firefox instead</div>
  	</div>
 
   <isgi-component lang="en" url="https://api.poleterresolide.fr/cds/isgi/data"></isgi-component>

 <!-- The file is generated when we launch in console: npm run build
         then push on github branch master and tag to version 0.0.5
     Modify the url according to your own configuration -->
	<!-- <script  src="https://api.poleterresolide.fr/webcomponents/isgi-component-vjs_0.6.0.js"/></script>
	 -->
