<?php 
?>

  
  	<aeris-theme id="theme2" active="true" primary="#006699" emphasis="#39B062"> </aeris-theme>
 
   <isgi-component lang="en" url="https://api.poleterresolide.fr/cds/isgi/data"></isgi-component>

 <!-- The file is generated when we launch in console: npm run build
         then push on github branch master and tag to version 0.0.5
     Modify the url according to your own configuration -->
	<script  src="https://api.poleterresolide.fr/webcomponents/isgi-component-vjs_0.2.8.js"/></script>