<?php
?>
<h3>Isgi Component</h3>

<a href="<?=APP_URL?>/tests/isgi-component-vjs/">Prototype Isgi Vuejs Component</a>

<h3>Geomagnetism on map</h3>

<a href="<?=APP_URL?>/tests/catalog-component-vjs/">Prototype Catalogue Component ( branch master)</a>

<h3>Geotiff integration 1</h3>

<a href="<?=APP_URL?>/tests/geotiff-visualizer/">Prototype Catalogue with Geotiff (branch geotiff version 2.13)</a>

<h3>Geotiff integration 2</h3>

<a href="<?=APP_URL?>/tests/geotiff-visualizer/page2.php">Prototype Catalogue with Geotiff (branch geotiff version 2.14)</a>
