<?php
?>
<h3>Isgi Component</h3>

<a href="<?=APP_URL?>/tests/isgi-component-vjs/">Prototype Isgi Vuejs Component</a>

<h3>Catalog ForM@Ter</h3>
<dl>
  <dt>Nouvelle version</dt>
  <dd>
    <a href="<?=APP_URL?>/tests/metadata-component-vjs/">Prototype Metadata vuejs application</a>
  </dd>
</dl>
<dl>
  <dt>Antique version</dt>
  <dd>
    <a href="<?=APP_URL?>/tests/catalog-component-vjs/">Prototype Catalogue Component </a>
  </dd>
</dl>
<h3>Le composant formater-geotiff-serie-vjs</h3>
<a href="<?=APP_URL?>/tests/geotiff-serie-component/">Prototype Geotiff Serie Component </a>

<h3>Le composant formater-geotiff-visualizer-vjs</h3>
<ul>
<li><a href="<?=APP_URL?>/tests/geotiff-visualizer/zenodo/?zid=177200">A partir d'un identifiant zenodo dans l'url</a></li>
<li><a href="<?=APP_URL?>/tests/geotiff-visualizer/">Vers Abana en Turquie (2 sous-fauchées)</a></li>
<li><a href="<?=APP_URL?>/tests/geotiff-visualizer/rome">Vers Rome (3 sous-fauchées)</a></li>
<li><a href="<?=APP_URL?>/tests/geotiff-visualizer/client-file">A partir de fichiers de l'utilisateur</a></li>
</ul>

<h3>Un composant pour visualiser les métadatas et les produits gep</h3>
<ul>
<li><a href="<?=APP_URL?>/tests/geotiff-visualizer/gep">A partir de l'exemple sur gep</a></li>
</ul>