<?php
?>
<header class="site-header">
<div id="header" class="container">
<a class="site-header-logo mt-1" href="<?=APP_URL?>"><img src="<?=APP_URL?>/images/logo-formater-transparent.png" alt="API ForM@Ter" height="60px"></a>
<nav class="site-header-nav">

<a class="site-header-nav-item" href="https://www.poleterresolide.fr/">Portal</a>
<a class="site-header-nav-item" href="<?=APP_URL?>/tests">Tests</a>
<a class="site-header-nav-item" href="https://github.com/terresolide/api.formater/wiki">API Docs</a>
<a class="site-header-nav-item" href="https://github.com/terresolide/api.formater/">On GitHub</a>

</nav>
</div>
</header>